repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        name: Check JSON
        description: This hook checks json files for parseable syntax.
      - id: check-yaml
        name: Check Yaml
        description: This hook checks yaml files for parseable syntax.
        args: ['--allow-multiple-documents']
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-format
        args: ["--verbose"]
        description: Python formatting
      - id: ruff-check
        description: Python linting
        args: ["--extend-select", "I", "--fix", "--exit-non-zero-on-fix"]
